version: "2"
services:
    bookstack:
        image: lscr.io/linuxserver/bookstack
        container_name: bookstack
        environment:
            - PUID=1000
            - PGID=1000
            - APP_URL=
            - DB_HOST=bookstack_db
            - DB_USER=bookstack
            - DB_PASS=123456
            - DB_DATABASE=bookstackapp
        volumes:
            - /path/to/data:/config
        ports:
            - 6875:80
        restart: unless-stopped
        depends_on:
            - bookstack_db
    bookstack_db:
        image: lscr.io/linuxserver/mariadb
        container_name: bookstack_db
        environment:
            - PUID=1000
            - PGID=1000
            - MYSQL_ROOT_PASSWORD=123456
            - TZ=Asia/Tehran
            - MYSQL_DATABASE=bookstackapp
            - MYSQL_USER=bookstack
            - MYSQL_PASSWORD=123456
        volumes:
            - /path/to/data:/config
        restart: unless-stopped
